/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package prativa_panday_p0p2;

import org.junit.Test;

import com.prativa_panday_p0p2.driver.Library;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
