/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.prativa_panday_p0p2.driver;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
